---
repos:
  - repo: local
    hooks:
      - id: bandit
        name: Bandit Security Check
        entry: .githooks/pre-commit-bandit
        language: script
        types: [python]
        files: '^(api_app|airlock_processor|resource_processor|cli|e2e_tests)/.*\.py$'
        exclude: '^(api_app|airlock_processor|resource_processor|cli|e2e_tests)/tests?/.*\.py$'
